- hosts: webservers
  become: true
  tasks:
  - name: Install Packages
    apt: 
      name:
      - build-essential
      - npm
      - nodejs-legacy
      - git
      - mcrypt
      - nginx
      - curl
    state: present
    autoclean: yes

  - name: Install pm2
    npm: name=pm2 global=yes production=yes